### ISSUE TITLE
Tournament page is overflowing 

### ISSUE THREAD

**Issue by mpellouin** [LisaGHeclys/Tournament-Pool#85]
Is it supposed to be like that?

[Screencast_20241112_111218.webm](https://github.com/user-attachments/assets/b0a87770-58d3-48c9-b5c5-ae2a8b2a2981)

**Comment by LisaGHeclys** [comment]
**Describe the bug**
Two pages are experiencing layout overflow issues:
- `show/[id]`
- `user/tournament/[id]`
![image](https://github.com/user-attachments/assets/fb72bad4-403d-437f-b959-b66d3b9c17b3)


**To Reproduce**
Steps to reproduce the behavior:
1. `npm run build`
2. `npm run start`
3. Navigate to either of the pages above and select a tournament that has points filled in.
4. Observe the layout overflow error.

**Expected behavior**
It shouldn't be overflowing, it's supposed to look the same as the display when there is no points.
![image](https://github.com/user-attachments/assets/3f817938-1ce8-4ffa-8d8c-9e99210367fc)
![image](https://github.com/user-attachments/assets/806b200c-da5f-4f1e-9764-75f521ec9709)

**Desktop:**
 - OS: any
 - Browser [e.g. chrome, safari] : any
